baseURL: https://dhruvi-mundra.netlify.app/
languageCode: en-us
title: Dhruvi's Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      I am a student at London Business School and an ex-PwC Consultant. I am passionate about Product Management and look forward to intellectually stimulating opportunities.
    title: Hi, my name is Dhruvi!
  blog: {}
  contact:
    address:
      - city: London, W1T6AQ
        country: United Kingdom
        street: Fitzroy Street
        title: London
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: dhruvimundra2205@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7471199558
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Dhruvi Mundra
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
     # - icon: fa-twitter
      #   label: Twitter
      #   url: https://www.twitter.com
      # - icon: fa-facebook
      #   label: Facebook
      #   url: https://www.facebook.com
      # - icon: fa-instagram
      #   label: Instagram
      #   url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/dhruvimundra
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/dhruvimundra/
  image: ''
  name: Dhruvi
  navigation:
    button1:
      - name: View Portfolio
        url: https://dhruvimundraportfolio.my.canva.site/
    # button2:
    #   - name: Log In
    #     url: '#'
    links:
      - name: Home
        url: '#'
      - name: Product Management Cases
        url: blogs
      - name: Coding Case Studies
        url: pm_cases
      - name: CV
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: Casual Photo.jpg
      #  subtitle: Ipsum Dolor Sit Amet
        title: About me
        url: blogs/aliquam
      - image: Big Ben.jpg
      #  subtitle: Feugiat Amet Tempus
        title: CV
        url: blogs/tempus
      - image: tower bridge.jpg
       # subtitle: Lorem Etiam Nullam
        title: Product Management Case Studies
        url: blogs/magna
      - image: London Eye.webp
       # subtitle: Nisl Sed Aliquam
        title: Coding Case Studies
        url: blogs/ipsum
      # - image: pic05.jpg
      #   subtitle: Ipsum Dolor Sit Amet
      #   title: Consequat
      #   url: blogs/ipsum
      # - image: pic06.jpg
      #   subtitle: Feugiat Amet Tempus
      #   title: Etiam
      #   url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Being a Management Consultant at PwC opened doors to understanding companies and users at a much deeper level. At DoWell Research, a product development firm, my interest in Product Management strengthened since it exposed me to user experience market research. I worked with clients like Google, YouTube and Spotify to help improve their product offerings.



At London Business School, I have taken up subjects like Product Management, Strategy and Data Science. This couple with my education in Statistics provides me with a strong analytical base that helps me find hidden insights within large sets of data.



My experience with 5+ NGOs in the past has given me extensive understanding of human behaviour. I wish to utilize my skills to build products that create an impact in the world."
    title: This is my story!
    url: blogs
